<?php

namespace Tests\Dependency\Traits;

use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\Artisan;
use Database\Seeders\RefreshDatabase\RefreshDatabaseSeeder;
use Illuminate\Support\Facades\Storage;

trait FreshSeedOnce
{
    /**
     * After the first run of setUp "migrate:fresh --seed"
     * @return void
     */
    protected function setUp(): void
    {
        parent::setUp();
        $seeders = [
            "cache:clear"
        ];
        array_walk($seeders, function ($seed) {
            Artisan::call($seed);
        });
    }

    /**
     * delete all files
     */
    protected function tearDown(): void
    {
        Storage::deleteDirectory("public") ;
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

}
