<?php

namespace App\Models;

use App\Core\Interfaces\BasktableInterface;
use App\Core\Traits\HasFilterTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Support\Str;

class Serial extends Model implements BasktableInterface
{
    use HasFactory, HasFilterTrait;

    protected $fillable = [
        "slug",
        "user_id",
        "title",
        "description",
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function($serial){
            $serial->slug = Str::uuid();
        });
    }

    public function episodes()
    {
        return $this->hasMany(PostSerial::class, "serial_id");
    }

    public function posts()
    {
        return $this
            ->belongsToMany(Post::class)
            ->withPivot([
                "title",
                "description",
                "is_locked",
                "priority",
            ]);
    }

    public function prices()
    {
        return $this->morphMany(Price::class, "priceable");
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function baskets()
    {
        return $this->morphToMany(Basket::class , "basketable" , "basketables") ;
    }
}
